[project]
name = "scryfall-telegram"
version = "2.5.1"
description = "Telegram bot backed by the Scryfall.com Magic:The Gathering API. Runs Serverless."
readme = "README.md"
requires-python = ">= 3.13"
authors = [{ name = "Oliver Hofkens", email = "oliver@hofkens.eu" }]
dependencies = [
    "pyxdameraulevenshtein>=1.9.0",
    "requests>=2.32.5",
    "structlog>=25.5.0",
]

[dependency-groups]
dev = ["pytest>=9.0.2", "pytest-cov>=7.0.0", "ruff>=0.14.10"]

[tool.poe.tasks.lint]
sequence = [
    {cmd = "ruff check"},
    {cmd = "ruff format --check"}
]

[tool.poe.tasks.test]
env = { STAGE = "staging" }
cmd = "pytest tests/unit/ tests/integration/"

[tool.poe.tasks.package]
shell = """
rm -rf .build
mkdir .build
cp -R scryfall_telegram/ .build/scryfall_telegram
uv export --frozen --no-dev --no-editable -o .build/requirements.txt
uv pip install \
    --no-installer-metadata \
    --no-compile-bytecode \
    --python-platform x86_64-manylinux2014 \
    --python 3.13 \
    --target .build/package/ \
    -r .build/requirements.txt
"""

[tool.pytest]
minversion = "9.0"
addopts = ["--tb=short", "--cov=.", "--cov-branch", "--cov-report=term-missing"]
testpaths = ["tests"]

[tool.uv.build-backend]
module-name = "scryfall_telegram"
module-root = ""

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"
